### ISSUE TITLE
I can't Install PanOS 10 Sun Valley!

### ISSUE THREAD

**Issue by MasterOpel** [orangegrouptech/Biohazards-from-orangegrouptech#3]
#This happens when I attempt to Install PanOS 10 Sun Valley:
![image](https://user-images.githubusercontent.com/104687131/169710687-b6e5560f-e0ba-46a9-90cc-1948e079568d.png)

**Comment by orangegrouptech** [comment]
https://github.com/orangegrouptech/PanOS-10-Sun-Valley-1.0 I've released the source code to Install PanOS 10 Sun Valley here, you can compile your own version and bypass the authentication system entirely
